<?php
// add_action('init', 'primer_register_manager_role', 0);
function primer_register_manager_role() {
  add_role('manager', 'Manager', array(
    // Wordpress Core
    'activate_plugins'        => false,
    'create_posts'            => true,
    'create_users'            => true,
    'customize'               => false,
    'delete_others_pages'     => true,
    'delete_others_posts'     => true,
    'delete_pages'            => true,
    'delete_plugins'          => false,
    'delete_posts'            => true,
    'delete_private_pages'    => true,
    'delete_private_posts'    => true,
    'delete_published_pages'  => true,
    'delete_published_posts'  => true,
    'delete_site'             => false,
    'delete_themes'           => false,
    'delete_users'            => true,
    'edit_dashboard'          => true,
    'edit_others_pages'       => true,
    'edit_others_posts'       => true,
    'edit_pages'              => true,
    'edit_plugins'            => false,
    'edit_posts'              => true,
    'edit_private_pages'      => true,
    'edit_private_posts'      => true,
    'edit_published_pages'    => true,
    'edit_published_posts'    => true,
    'edit_theme_options'      => true,
    'edit_themes'             => false,
    'edit_users'              => true,
    'export'                  => false,
    'import'                  => false,
    'install_languages'       => false,
    'install_plugins'         => false,
    'install_themes'          => false,
    'list_users'              => true,
    'manage_categories'       => true,
    'manage_links'            => true,
    'manage_options'          => false,
    'moderate_comments'       => true,
    'promote_users'           => true,
    'publish_pages'           => true,
    'publish_posts'           => true,
    'read_private_pages'      => true,
    'read_private_posts'      => true,
    'read'                    => true,
    'remove_users'            => true,
    'resume_plugins'          => false,
    'resume_themes'           => false,
    'switch_themes'           => false,
    'unfiltered_html'         => true,
    'unfiltered_upload'       => true,
    'update_core'             => false,
    'update_plugins'          => false,
    'update_themes'           => false,
    'upload_files'            => true,
    'view_site_health_checks' => false,

    // Gravity Forms
    'gravityforms_create_form'      => true,
    'gravityforms_delete_entries'   => true,
    'gravityforms_delete_forms'     => true,
    'gravityforms_edit_entries'     => true,
    'gravityforms_edit_entry_notes' => true,
    'gravityforms_edit_forms'       => true,
    'gravityforms_edit_settings'    => false,
    'gravityforms_export_entries'   => true,
    'gravityforms_feed'             => true,
    'gravityforms_uninstall'        => false,
    'gravityforms_view_entries'     => true,
    'gravityforms_view_entry_notes' => true,
    'gravityforms_view_settings'    => false,

    // Safe Redirect Manager
    'srm_manage_redirects' => true,
  ));
}
?>